# Generated by Django 2.0.6 on 2019-12-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quenchApp', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quenchApp/media/'),
        ),
    ]
