# Generated by Django 2.0.6 on 2019-12-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quenchApp', '0004_auto_20191223_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
