# Generated by Django 2.0.6 on 2020-01-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quenchApp', '0008_auto_20200105_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
